# See with https://github.com/google/mono_repo.dart for details on this file
dart:
- 2.4.0
- dev

stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.4.0]
- unit_test:
  - group:
    - test

cache:
  directories:
  - .dart_tool/build
