name: vote
description: >-
  A number of voting methods implemented in Dart with base classes that allow
  easy comparison between implementations.
version: 0.1.0
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/vote.dart

environment:
  sdk: '>=2.3.0-dev.0.3 <3.0.0'

dependencies:
  collection: ^1.0.0
  graphs: ^0.2.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.6.0
