steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t', '${_IMAGE}',
            '--build-arg', 'channel=${_FLUTTER_CHANNEL}',
            '.'
    ]
  - name: '${_IMAGE}'
    entrypoint: firebase
    args: [
      'deploy', '--project=$PROJECT_ID', '--only', 'hosting:vote-dart'
    ]
    dir: vote_demo

substitutions:
  _FLUTTER_CHANNEL: master
  _IMAGE: the-builder
