name: vote
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/vote.dart

environment:
  sdk: '>=2.3.0-dev <3.0.0'

dependencies:
  tuple: ^1.0.1

dev_dependencies:
  test: ^1.0.0
