name: vote_demo
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.14.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  provider: ^6.0.0
  url_launcher: ^6.0.9
  vote: any
  vote_widgets: any

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.19.3

dependency_overrides:
  vote:
    path: ../vote
  vote_widgets:
    path: ../vote_widgets

flutter:
  uses-material-design: true
