# Holding off testing since this requires Flutter @ master
# See with https://github.com/google/mono_repo.dart for details on this file
stages:
- smoke_test:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
    dart: [dev]
  - group:
    - dartanalyzer: --fatal-warnings .
    dart: [2.5.0-dev.1.0]

cache:
  directories:
  - .dart_tool/build
