# Holding off testing since this requires Flutter @ master
# See with https://github.com/google/mono_repo.dart for details on this file
stages:
- smoke_test:
  - group:
    - format
    - analyze: --fatal-infos .
    dart: [dev]
  - group:
    - dartanalyzer: .
    dart: [2.12.0]

cache:
  directories:
  - .dart_tool/build
