name: knarly

environment:
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  flutter_web: any
  flutter_web_ui: any
  provider: any
  vote:
    path: ../vote

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^2.0.0
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  provider:
    git:
      url: https://github.com/kevmoo/provider
      ref: flutter_web
