name: vote_demo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  flutter:
    sdk: flutter
  provider: ^5.0.0
  vote:
    path: ../vote

dev_dependencies:
  build_runner: ^2.0.5
  build_web_compilers: ^3.0.0
  pedantic: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
  - family: RobotoMono
    fonts:
    - asset: assets/fonts/RobotoMono-Regular.ttf
