# Created with package:mono_repo v5.0.2
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2.3.4
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 5.0.2
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "smoke_test; Dart 2.14.0; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:vote;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:vote
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
        run: dart pub upgrade
      - name: vote; dart analyze
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
        run: dart analyze
  job_003:
    name: "smoke_test; Dart dev; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:vote;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:vote
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
        run: dart pub upgrade
      - name: "vote; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "vote; dart analyze --fatal-infos ."
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
        run: dart analyze --fatal-infos .
  job_004:
    name: "unit_test; Dart 2.14.0; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:vote;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0;packages:vote
            os:ubuntu-latest;pub-cache-hosted;dart:2.14.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: "2.14.0"
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
        run: dart pub upgrade
      - name: vote; dart test
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; Dart dev; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2.1.6
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:vote;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:dev;packages:vote
            os:ubuntu-latest;pub-cache-hosted;dart:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: dev
      - id: checkout
        uses: actions/checkout@v2.3.4
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
        run: dart pub upgrade
      - name: vote; dart test
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
        run: dart test
    needs:
      - job_001
      - job_002
      - job_003
