# Created with package:mono_repo v6.5.7
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.5.7
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "smoke_test; Dart 3.0.0; PKG: vote; `dart analyze`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0;packages:vote;commands:analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0;packages:vote
            os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: "3.0.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
      - name: vote; dart analyze
        run: dart analyze
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
  job_003:
    name: "smoke_test; Dart dev; PKG: vote; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:vote;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:vote
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
      - name: "vote; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
      - name: "vote; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
  job_004:
    name: "smoke_test; Flutter master; PKG: vote_demo; `dart format --output=none --set-exit-if-changed .`, `flutter analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:vote_demo;commands:format-analyze_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:vote_demo
            os:ubuntu-latest;pub-cache-hosted;sdk:master
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_demo_pub_upgrade
        name: vote_demo; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote_demo
      - name: "vote_demo; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.vote_demo_pub_upgrade.conclusion == 'success'"
        working-directory: vote_demo
      - name: "vote_demo; flutter analyze --fatal-infos ."
        run: flutter analyze --fatal-infos .
        if: "always() && steps.vote_demo_pub_upgrade.conclusion == 'success'"
        working-directory: vote_demo
  job_005:
    name: "unit_test; Dart 3.0.0; PKG: vote; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0;packages:vote;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0;packages:vote
            os:ubuntu-latest;pub-cache-hosted;sdk:3.0.0
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: "3.0.0"
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
      - name: vote; dart test
        run: dart test
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_006:
    name: "unit_test; Dart dev; PKG: vote; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:vote;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:dev;packages:vote
            os:ubuntu-latest;pub-cache-hosted;sdk:dev
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: dev
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_pub_upgrade
        name: vote; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote
      - name: vote; dart test
        run: dart test
        if: "always() && steps.vote_pub_upgrade.conclusion == 'success'"
        working-directory: vote
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
  job_007:
    name: "unit_test; Flutter master; PKG: vote_demo; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:vote_demo;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:master;packages:vote_demo
            os:ubuntu-latest;pub-cache-hosted;sdk:master
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: master
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - id: vote_demo_pub_upgrade
        name: vote_demo; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: vote_demo
      - name: vote_demo; flutter test
        run: flutter test
        if: "always() && steps.vote_demo_pub_upgrade.conclusion == 'success'"
        working-directory: vote_demo
    needs:
      - job_001
      - job_002
      - job_003
      - job_004
